config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :customers do
    member do
      get 'cars'
    end
  end
  resources :cars
  resources :coupons

  root "customers#index"
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :customer

  #Validation:
  validates :customer_id, :car_model, :color, :last_servicing_date, :repair_part, presence: true
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  #Generate a coupon code before create record
  before_create :generate_coupon

  has_many :coupon_dates, dependent: :destroy

  def generate_coupon
    self.coupon_code = unique_token
  end

  #Trigger coupon code email
  def self.offer_coupon
    coupon_dates = CouponDate.where(send_date: Date.today)
    EMAIL_LOGGER.info("sending email to : #{coupon_dates}")
    EMAIL_LOGGER.info("coupon_dates count: #{coupon_dates.count}")
    coupon_dates.each do |coupon_date|
      coupon = coupon_date.coupon
      #Sending the email
      msg = CouponMailer.offer_coupon(coupon).deliver_now
      EMAIL_LOGGER.info("BODY: #{msg.body}")
    end
  end

  private
  #generating a uniq code
  def unique_token
    token = random_string
    loop do
      break unless Coupon.match_token?(token)
      token = random_string
    end
    token
  end

  def self.match_token?(token)
    where(coupon_code: token).present?
  end

  def random_string
    (0..rand(6..15)).map { (65 + rand(26)).chr }.join
  end

end

app/models/coupon_date.rb
class CouponDate < ActiveRecord::Base
  belongs_to :coupon
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  #Validation:
  validates :email, :first_name, :last_name, :phone, :address, presence: true
  validates_formatting_of :email, using: :email, if: '!email.blank?'

  #association with cars:
  # Customer can have many cars
  # Car details will be deleted with customer destroy so added dependent: :destroy
  has_many :cars, dependent: :destroy


  #After how many days we want to send notification to customer
  DEFAULT_INTERVAL = 30

  #Class method to send notification
  def self.next_servicing
    #(Date.today-Customer::DEFAULT_INTERVAL.days) :: Finding 30 days before date
    @cars = Car.where(last_servicing_date: (Date.today-Customer::DEFAULT_INTERVAL.days))
    @cars.each do |car|
      #Sending eails
      msg = ServicingNotificationMailer.servicing_notification(car).deliver_now
      EMAIL_LOGGER.info("sending email to : #{car.customer.email}")
      EMAIL_LOGGER.info("BODY: #{msg}")
    end
  end

  def full_name
    first_name + " " + last_name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  #only logged in user can access this page
  before_action :authenticate_user!

  def show
    @car = Car.find(params[:id])
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  #only logged in user can access this page
  before_action :authenticate_user!

  def index
    @coupons = Coupon.all
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  #only logged in user can access this page
  before_action :authenticate_user!

  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def cars
    @customer = Customer.find(params[:id])
    @cars = @customer.cars
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/coupens_helper.rb
module CoupensHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/cars/show.html.erb
<table class="table table-hover">
   <thead>
     <tr>
       <th>Content</th>
       <th>Car Detail</th>
     </tr>
   </thead>
   <tbody>
      <tr>
        <td>Car Model</td>
        <td><%=@car.car_model%></td>
      </tr>
      <tr>
        <td>Color</td>
        <td><%=@car.color%></td>
      </tr>
      <tr>
        <td>Last Servicing Date</td>
        <td><%=@car.last_servicing_date%></td>
      </tr>
      <tr>
        <td>Repair part</td>
        <td><%=@car.repair_part%></td>
      </tr>
    </tbody>
</table>

app/views/coupons/_coupons.html.erb
<tr>
  <td><%=coupons.coupon_code%></td>
  <td><%=coupons.description%></td>
  <td><%= coupons.coupon_dates.map(&:send_date).join(", ") %></td>
</tr>

app/views/coupons/index.html.erb
<h3>Coupon Page</h3>
<table class="table table-hover">
   <thead>
     <tr>
       <th>Code</th>
       <th>Description</th>
       <th>Send dates</th>
     </tr>
   </thead>
   <tbody>
    <%= render :partial => 'coupons', :collection => @coupons %>
   </tbody>
 </table>

app/views/customers/_car_detail.html.erb
<tr>
  <td><%=car_detail.car_model%></td>
  <td><%=car_detail.color%></td>
  <td><%=car_detail.last_servicing_date%></td>
  <td><%=car_detail.repair_part%></td>
  <td><%= link_to 'Show', car_path(car_detail), class: 'btn btn-primary' %></td>
</tr>

app/views/customers/_customer_detail.html.erb
<tr>
  <td><%=customer_detail.first_name%></td>
  <td><%=customer_detail.last_name%></td>
  <td><%=customer_detail.email%></td>
  <td><%=customer_detail.phone%></td>
  <td><%=customer_detail.address%></td>
  <td><%=customer_detail.last_visit_date%></td>
  <td><%=customer_detail.cars.count%></td>
  <td><%= link_to 'Show',  customer_path(customer_detail), class: 'btn btn-primary'%></td>
</tr>

app/views/customers/cars.html.erb
<table class="table table-hover">
   <thead>
     <tr>
       <th>Car Model</th>
       <th>Color</th>
       <th>Last Servicing Date</th>
       <th>Repair Part</th>
       <th>show</th>
     </tr>
   </thead>
   <tbody>
    <%= render :partial => 'car_detail', :collection => @cars %>
   </tbody>
 </table>

app/views/customers/index.html.erb
<table class="table table-hover">
   <thead>
     <tr>
       <th>Firstname</th>
       <th>Lastname</th>
       <th>Email</th>
       <th>Phone</th>
       <th>Address</th>
       <th>Last Visit Date</th>
       <th>Car(s)</th>
       <th>#</th>
     </tr>
   </thead>
   <tbody>
    <%= render :partial => 'customer_detail', :collection => @customer %>
   </tbody>
 </table>

app/views/customers/show.html.erb
<table class="table table-hover">
   <thead>
     <tr>
       <th>Content</th>
       <th>Customer Detail</th>
     </tr>
   </thead>
   <tbody>
      <tr>
        <td>Firstname</td>
        <td><%=@customer.first_name%></td>
      </tr>
      <tr>
        <td>Lastname</td>
        <td><%=@customer.last_name%></td>
      </tr>
      <tr>
        <td>Email</td>
        <td><%=@customer.email%></td>
      </tr>
      <tr>
        <td>Phone</td>
        <td><%=@customer.phone%></td>
      </tr>
      <tr>
        <td>Address</td>
        <td><%=@customer.address%></td>
      </tr>
      <tr>
        <td>Last Visit Date</td>
        <td><%=@customer.last_visit_date%></td>
      </tr>
      <tr>
        <td colspan="2"><%= link_to 'Car details', cars_customer_path(@customer), class: 'btn btn-primary'%></td>
      </tr>
    </tbody>
 </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ServiceCenter" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ServiceCenter", root_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Customers", customers_path%></li>
              <li><%= link_to "Coupons", coupons_path  %></li>
              <li><li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>